### ISSUE TITLE
Error: no Auth Provider found

### ISSUE THREAD

**Issue by mdarin** [yaacov/kubectl-sql#15]
Hi, Yaacov!

I just `clone` and `make` the project.

My `kubeconfig` has got multi context. 

I try to execute example query and get an error `Error: no Auth Provider found for name "oidc"`

<img width="580" alt="Image" src="https://github.com/user-attachments/assets/4ab9e9e3-383c-466a-82ea-f7e504cc95a2" />

```sh
cat $HOME/.kube/config
```

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0....
    server: https://....
  name: cluster
- cluster:
   # ....
contexts:
- context:
    cluster: cluster
    user: cluster-admin
  name: cluster-admin@cluster
#....
current-context: ...
kind: Config
preferences: {}
users:
- name: cluster-admin
  user:
    client-certificate-data: LS0...
    client-key-data: LS0...
- name: mi...
  user:
    auth-provider:
      config:
        client-id: ...
        client-secret: 5G...
        id-token: eyJh...
        idp-issuer-url: https://keycloak.cloud....
        refresh-token: eyJh...
      name: oidc
```

May by I do anything wrong?

**Comment by yaacov** [comment]
@mdarin can you try - https://github.com/yaacov/kubectl-sql/pull/16 ?

**Comment by mdarin** [comment]
_a. does it work correctly for you if you when you clean up the kubeconfig and use simpler config ?_
>> yes, but with some nuance..

if I use simple config with following kind of authorization, I have a success.
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0...
    server: https....
  name: cluster
contexts:
- context:
    cluster: cluster
    user: cluster-admin
  name: cluster-admin@cluster
current-context: cluster-admin@cluster
kind: Config
preferences: {}
users:
- name: cluster-admin
  user:
    client-certificate-data: LS0...
    client-key-data: LS0...
```
<img width="731" alt="Image" src="https://github.com/user-attachments/assets/e9c45734-95b7-4a00-986a-9be6aa8bd57e" />

But for this one auth configuration with auth provider defined I encounter an error.
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0...
    server: https://k8s.cloud.....
  name: .....
contexts:
- context:
    cluster: ...
    namespace: default
    user: mi....
  name: salt-dev
current-context: ....
kind: Config
preferences: {}
users:
- name: mi...
  user:
    auth-provider:
      config:
        client-id: ....
        client-secret: 5G...
        id-token: eyJh...
        idp-issuer-url: https://keycloak.cloud....
        refresh-token: eyJh...
      name: oidc
```

_b. a. does it work correctly for you if you when you clean up the kubeconfig and use simpler config ?_
 
and 

_c. c. does it happen for all clusters ?_

>> You can create a couple of your own clusters(and context respectively) and try to interact with multi context kubeconfig. But, on my opinion, the error occurs for specific kind of user auth method `auth-provider`.
